/*
 * action types
 */

export const SET_VIEW_MODE = "SET_VIEW_MODE";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const LOAD_FAMILY_TREE_SUCCESS = "LOAD_FAMILY_TREE_SUCCESS";
export const LOAD_PEOPLE_LIST_SUCCESS = "LOAD_PEOPLE_LIST_SUCCESS";
export const LOAD_PERSON_DETAILS_SUCCESS = "LOAD_PERSON_DETAILS_SUCCESS";
export const UPDATE_PERSON_DETAILS_SUCCESS = "UPDATE_PERSON_DETAILS_SUCCESS";
export const CREATE_PERSON_DETAILS_SUCCESS = "CREATE_PERSON_DETAILS_SUCCESS";
export const SET_SELECTED_PERSON = "SET_SELECTED_PERSON";

/*
 * other constants
 */

export const ViewMode = {
  SHOW_FAMILY_TREE: "SHOW_FAMILY_TREE",
  SHOW_DETAIL: "SHOW_DETAIL",
  SHOW_EDIT: "SHOW_EDIT",
  SHOW_UPLOAD: "SHOW_UPLOAD",
};
