/*
 * action types
 */

export const SET_VIEW_MODE = "SET_VIEW_MODE";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const LOAD_FAMILY_TREE_SUCCESS = "LOAD_FAMILY_TREE_SUCCESS";
export const LOAD_PEOPLE_LIST_SUCCESS = "LOAD_PEOPLE_LIST_SUCCESS";
export const LOAD_PERSON_DETAILS_SUCCESS = "LOAD_PERSON_DETAILS_SUCCESS";
export const LOAD_PERSON_DETAILS_FOR_UPDATE_SUCCESS =
  "LOAD_PERSON_DETAILS_FOR_UPDATE_SUCCESS";
export const UPDATE_PERSON_DETAILS_SUCCESS = "UPDATE_PERSON_DETAILS_SUCCESS";
export const CREATE_PERSON_DETAILS_SUCCESS = "CREATE_PERSON_DETAILS_SUCCESS";
export const SET_SELECTED_PERSON = "SET_SELECTED_PERSON";
export const DELETE_PERSON_SUCCESS = "DELETE_PERSON_SUCCESS";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const LOAD_USER_LIST_SUCCESS = "LOAD_USER_LIST_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const LOAD_PICTURE_DETAILS_SUCCESS = "LOAD_PICTURE_DETAILS_SUCCESS";
export const DELETE_PICTURE_SUCCESS = "DELETE_PICTURE_SUCCESS";
export const UPDATE_PICTURE_DETAILS_SUCCESS = "UPDATE_PICTURE_DETAILS_SUCCESS";
export const SET_SELECTED_PICTURE = "SET_SELECTED_PICTURE";
/*
 * other constants
 */

export const ViewMode = {
  SHOW_FAMILY_TREE: "SHOW_FAMILY_TREE",
  SHOW_DETAIL: "SHOW_DETAIL",
  SHOW_EDIT: "SHOW_EDIT",
  SHOW_ADD: "SHOW_ADD",
  SHOW_UPLOAD: "SHOW_UPLOAD",
  SHOW_USERS: "SHOW_USERS",
  SHOW_PROFILE: "SHOW_PROFILE",
  SHOW_PICTURE_DETAIL: "SHOW_PICTURE_DETAIL",
};
